# Generated by Django 3.2.6 on 2021-08-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerKhata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='AmountGiven',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='AmountGot',
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(null=True)),
                ('AmountGiven', models.IntegerField(null=True)),
                ('AmountGot', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomerKhata.customer')),
            ],
        ),
    ]
