# Generated by Django 3.2.6 on 2021-08-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerKhata', '0002_auto_20210822_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
